### ISSUE TITLE
Have you seen this error by any chance?

### ISSUE THREAD

**Issue by no0p** [y310/kodama#2]
symbol lookup error: /var/lib/gems/1.9.1/gems/ruby-binlog-0.1.8/lib/binlog.so: undefined symbol: rb_thread_blocking_region_begin

Thanks -- I'm looking forward to trying this out.

**Comment by y310** [comment]
This is issue of ruby 1.9.3-p194 (maybe, <= p194).
https://bugs.ruby-lang.org/issues/6607
And it is already fixed latest version (ruby 1.9.3-p385).
Please try again with latest ruby 1.9.3 .

**Comment by jage** [comment]
I had similar issues. All issues gone in Ruby 1.9.3-p392 and 2.0.0-p0 since [ruby-binlog 0.1.9](https://bitbucket.org/winebarrel/ruby-binlog) was released.

**Comment by y310** [comment]
I released kodama 0.1.1.
This includes `'ruby-binlog', '>= 0.1.9'` constraint. e516e9f54ffcaf9a92971d1e9b2b8a68743a0625
This seems to work for my project.
Thanks for the report > @bdigital @jage
