### ISSUE TITLE
Kodama hangs when restarting with binlog_position_file

### ISSUE THREAD

**Issue by bjoernhaeuser** [y310/kodama#3]
Hi,

when using `binlog_position_file` the programrm hangs on second startup.

This is my code:

``` ruby
Kodama::Client.start(:host => 'xxx.xxx.xxx.xxx', :username => 'root', :password => '') do |c|
  c.binlog_position_file = 'position.log'
  c.log_level = :info
  c.connection_retry_limit = 100
  c.connection_retry_wait = 3
  c.gracefully_stop_on :QUIT, :INT

  c.on_row_event do |event|
    if event.table_name == "orders" then
      eventHandler = Event.new(columns)
      eventHandler.handle(event)
    end
  end
end
```

On first startup everything works fine. But after stopping it with CTRL+C and trying to restart it, the programm won't startup correctly. Dtrussing it gives me than:

```
SYSCALL(args)        = return
```

I need to `kill -9` the process to get my Terminal back.

Versions:

```
ruby 1.9.3p392 (2013-02-22 revision 39386) [x86_64-darwin12.3.0]
ruby-binlog (0.1.9)
kodama (0.1.1)
```

Thanks in advance
Björn

**Comment by y310** [comment]
I could not reproduce the problem.
Does this problem happen every time?
And if comment out `gracefully_stop_on` option, the problem still happens?

**Comment by bjoernhaeuser** [comment]
Sorry, never tried this again. Closing this now :(
